packages:
  - server
  - agent
  - terminal-recorder
  - web
  - shared

minimumReleaseAgeExclude:
  - lucide-react@1.47.0

onlyBuiltDependencies:
  - esbuild

overrides:
  gitdiff-parser: 0.3.1

patchedDependencies:
  "@xterm/xterm@6.1.0-beta.304": web/patches/@xterm__xterm@6.1.0-beta.304.patch
  https-proxy-agent@9.1.0: agent/patches/https-proxy-agent@9.1.0.patch
